version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql8_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Neves123
      MYSQL_DATABASE: board
      MYSQL_USER: claudioneves
      MYSQL_PASSWORD: Neves123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
